name: Build firmware

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  KEYBOARD: moonlander
  KEYMAP: ilabutin

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
      - name: Checkout ZSA QMK
        uses: actions/checkout@v3
        with:
          repository: ilabutin/zsa_qmk_firmware
          fetch-depth: 1
          persist-credentials: false
          submodules: true
          path: 'zsa_qmk'

      - name: Checkout keymap
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
          submodules: true
          path: "zsa_qmk/keyboards/$KEYBOARD/keymaps/$KEYMAP"

      - name: Build
        id: build
        run: |
          qmk compile -kb "$KEYBOARD" -km "$KEYMAP"
      
          TARGET="$(echo "$KEYBOARD" | sed 's#/#_#g')_$KEYMAP"
          echo ::set-output name=artifact-name::${TARGET}
          echo "Artifact-name: ${{ steps.build.outputs.artifact-name }}"
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.build.outputs.artifact-name }}"
          path: |
            zsa_qmk/*.hex
            zsa_qmk/*.bin
        continue-on-error: true
