# This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the workflow will run
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
      - name: Checkout keymap
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
          submodules: true
          path: 'keymap'

      - name: Checkout ZSA QMK
        uses: actions/checkout@v3
        with:
          repository: ilabutin/zsa_qmk_firmware
          fetch-depth: 1
          persist-credentials: false
          submodules: true
          path: 'zsa_qmk'
          
      - name: Link keymap folder to QMK
        run: ln -s ${{ github.workspace }}/keymap ${{ github.workspace }}/zsa_qmk/keyboards/moonlander/keymaps/ilabutin
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cat zsa_qmk/keyboards/moonlander/keymaps/ilabutin/rules.mk
